# Weather Data for the corn belt

[https://daymet.ornl.gov/](https://daymet.ornl.gov/)

## Import Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import os
from dotenv import load_dotenv
import time
from io import StringIO

## Load Yield data

In [3]:
# I need fips to be a string in case there are leading zeros
yield_df = pd.read_csv('./County Corn Yield Data/corn_belt_yield.csv', dtype={"fips": str})
yield_df.head()

,state_name,state_alpha,state_ansi,county_ansi,fips,county_name,year,short_desc,unit_desc,statisticcat_desc,Value
0,ILLINOIS,IL,17,11,17011,BUREAU,2025,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",BU / ACRE,YIELD,225.9
1,ILLINOIS,IL,17,11,17011,BUREAU,2024,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",BU / ACRE,YIELD,240.8
2,ILLINOIS,IL,17,11,17011,BUREAU,2023,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",BU / ACRE,YIELD,223.5
3,ILLINOIS,IL,17,11,17011,BUREAU,2022,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",BU / ACRE,YIELD,225.1
4,ILLINOIS,IL,17,11,17011,BUREAU,2021,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",BU / ACRE,YIELD,203.5

## Checking Data

In [4]:
yield_df.shape

(24644, 11)

In [5]:
yield_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24644 entries, 0 to 24643
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   state_name         24644 non-null  object
 1   state_alpha        24644 non-null  object
 2   state_ansi         24644 non-null  int64
 3   county_ansi        24644 non-null  int64
 4   fips               24644 non-null  object
 5   county_name        24644 non-null  object
 6   year               24644 non-null  int64
 7   short_desc         24644 non-null  object
 8   unit_desc          24644 non-null  object
 9   statisticcat_desc  24644 non-null  object
 10  Value              24644 non-null  float64
dtypes: float64(1), int64(3), object(7)
memory usage: 2.1+ MB

In [6]:
yield_df.describe()

         state_ansi   county_ansi          year         Value
count  24644.000000  24644.000000  24644.000000  24644.000000
mean      28.079127     93.939012   2011.815533    147.829005
std       10.878044     57.255843      7.443268     38.241255
min       17.000000      1.000000   2000.000000      0.000000
25%       19.000000     45.000000   2005.000000    124.000000
50%       26.000000     91.000000   2011.000000    151.800000
75%       31.000000    139.000000   2018.000000    175.300000
max       55.000000    239.000000   2025.000000    253.600000

In [7]:
yield_df.describe(include='object')

,state_name,state_alpha,fips,county_name,short_desc,unit_desc,statisticcat_desc
count,24644,24644,24644,24644,24644,24644,24644
unique,13,13,1124,704,1,1,1
top,IOWA,IA,17011,JACKSON,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",BU / ACRE,YIELD
freq,2470,2470,26,231,24644,24644,24644

In [8]:
yield_df.isnull().sum()

state_name           0
state_alpha          0
state_ansi           0
county_ansi          0
fips                 0
county_name          0
year                 0
short_desc           0
unit_desc            0
statisticcat_desc    0
Value                0
dtype: int64

In [9]:
yield_df.duplicated().sum()

0

In [10]:
for i in yield_df.select_dtypes(include='object').columns:
    print(yield_df[i].value_counts())
    print("*"*30)

state_name
IOWA            2470
ILLINOIS        2417
INDIANA         2142
KENTUCKY        2092
KANSAS          2090
NEBRASKA        2069
OHIO            2051
MISSOURI        1967
MINNESOTA       1867
WISCONSIN       1577
MICHIGAN        1485
SOUTH DAKOTA    1363
NORTH DAKOTA    1054
Name: count, dtype: int64
******************************
state_alpha
IA    2470
IL    2417
IN    2142
KY    2092
KS    2090
NE    2069
OH    2051
MO    1967
MN    1867
WI    1577
MI    1485
SD    1363
ND    1054
Name: count, dtype: int64
******************************
fips
17011    26
27169    26
26161    26
26147    26
26115    26
         ..
29055     1
29119     1
29229     1
29209     1
21189     1
Name: count, Length: 1124, dtype: int64
******************************
county_name
JACKSON       231
WASHINGTON    217
JEFFERSON     199
CLAY          196
MONROE        184
             ...
MAGOFFIN        1
STONE           1
DENT            1
OWSLEY          1
ELLIOTT         1
Name: count, Length: 704, dtype: int64
******************************
short_desc
CORN, GRAIN - YIELD, MEASURED IN BU / ACRE    24644
Name: count, dtype: int64
******************************
unit_desc
BU / ACRE    24644
Name: count, dtype: int64
******************************
statisticcat_desc
YIELD    24644
Name: count, dtype: int64
******************************

## Latitude and Longitude of each County

To get the weather from Daymet, I need a latitude and longitude which I can get for each county to then apply the weather data to. 

[https://simplemaps.com/data/us-counties](https://simplemaps.com/data/us-counties)

In [11]:
coords_df = pd.read_csv('./County Corn Yield Data/uscounties.csv', dtype={"county_fips": str})
coords_df.head()

,county,county_ascii,county_full,county_fips,state_id,state_name,lat,lng,population
0,Los Angeles,Los Angeles,Los Angeles County,06037,CA,California,34.3219,-118.2247,9808667
1,Cook,Cook,Cook County,17031,IL,Illinois,41.8401,-87.8168,5182090
2,Harris,Harris,Harris County,48201,TX,Texas,29.8578,-95.3938,4838303
3,Maricopa,Maricopa,Maricopa County,04013,AZ,Arizona,33.3490,-112.4915,4559748
4,San Diego,San Diego,San Diego County,06073,CA,California,33.0343,-116.7350,3288774

In [12]:
coords_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3144 entries, 0 to 3143
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   county        3144 non-null   object
 1   county_ascii  3144 non-null   object
 2   county_full   3144 non-null   object
 3   county_fips   3144 non-null   object
 4   state_id      3144 non-null   object
 5   state_name    3144 non-null   object
 6   lat           3144 non-null   float64
 7   lng           3144 non-null   float64
 8   population    3144 non-null   int64
dtypes: float64(2), int64(1), object(6)
memory usage: 221.2+ KB

In [13]:
coords_df = coords_df[["county_fips", "lat", "lng"]]
coords_df.head()

  county_fips      lat       lng
0       06037  34.3219 -118.2247
1       17031  41.8401  -87.8168
2       48201  29.8578  -95.3938
3       04013  33.3490 -112.4915
4       06073  33.0343 -116.7350

In [14]:
coords_df = coords_df.rename(columns={"county_fips": "fips", "lat":"latitude", "lng":"longitude"})
coords_df.head()

    fips  latitude  longitude
0  06037   34.3219  -118.2247
1  17031   41.8401   -87.8168
2  48201   29.8578   -95.3938
3  04013   33.3490  -112.4915
4  06073   33.0343  -116.7350

### Merge the yield dataset with the coordinates

In [15]:
yield_df = yield_df.merge(coords_df, on="fips", how="left")
yield_df.head()

,state_name,state_alpha,state_ansi,county_ansi,fips,county_name,year,short_desc,unit_desc,statisticcat_desc,Value,latitude,longitude
0,ILLINOIS,IL,17,11,17011,BUREAU,2025,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",BU / ACRE,YIELD,225.9,41.4041,-89.5286
1,ILLINOIS,IL,17,11,17011,BUREAU,2024,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",BU / ACRE,YIELD,240.8,41.4041,-89.5286
2,ILLINOIS,IL,17,11,17011,BUREAU,2023,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",BU / ACRE,YIELD,223.5,41.4041,-89.5286
3,ILLINOIS,IL,17,11,17011,BUREAU,2022,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",BU / ACRE,YIELD,225.1,41.4041,-89.5286
4,ILLINOIS,IL,17,11,17011,BUREAU,2021,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",BU / ACRE,YIELD,203.5,41.4041,-89.5286

In [16]:
yield_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24644 entries, 0 to 24643
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   state_name         24644 non-null  object
 1   state_alpha        24644 non-null  object
 2   state_ansi         24644 non-null  int64
 3   county_ansi        24644 non-null  int64
 4   fips               24644 non-null  object
 5   county_name        24644 non-null  object
 6   year               24644 non-null  int64
 7   short_desc         24644 non-null  object
 8   unit_desc          24644 non-null  object
 9   statisticcat_desc  24644 non-null  object
 10  Value              24644 non-null  float64
 11  latitude           24644 non-null  float64
 12  longitude          24644 non-null  float64
dtypes: float64(3), int64(3), object(7)
memory usage: 2.4+ MB

### Make county locations without all of the years because Daymet returns all of the years together

In [17]:
county_locations = yield_df[["fips", "latitude", "longitude"]].drop_duplicates(subset="fips").reset_index(drop=True)
county_locations.head()

    fips  latitude  longitude
0  17011   41.4041   -89.5286
1  17015   42.0687   -89.9343
2  17073   41.3531   -90.1314
3  17085   42.3658   -90.2126
4  17103   41.7461   -89.3003

## Get weather data from Daymet

I am using the [Single Pixel Extraction Tool](https://daymet.ornl.gov/single-pixel-tool-guide).

In [18]:
DAYMET_URL = "https://daymet.ornl.gov/single-pixel/api/data"

In [19]:
# Make directory to save each of the weather files in
os.makedirs("daymet_counties", exist_ok=True)

In [20]:
# all_weather_data = []

for index, row in county_locations.iterrows():

    county_file = f"daymet_counties/daymet_{row["fips"]}.csv"

    # Skip the county if its file already exists.
    if os.path.exists(county_file):
        print(f"{index}/{len(county_locations)}: {row["fips"]} already completed")
        continue

    print(f"Downloading county {index + 1} of {len(county_locations)}:", row["fips"])
    
    parameters = {
        "lat": row["latitude"],
        "lon": row["longitude"],
        "vars": "tmax,tmin,srad,vp,swe,prcp,dayl",
        "start": "2000-01-01",
        "end": "2025-12-31"
    }

    try:

        r = requests.get(
            DAYMET_URL,
            params=parameters,
            timeout=120
        )
    
        r.raise_for_status()
        
        data = pd.read_csv(StringIO(r.text), skiprows=6)
    
        data["fips"] = row["fips"]
        data["latitude"] = row["latitude"]
        data["longitude"] = row["longitude"]
    
        # print(type(data))
        # print(data)
        # print("*"*30)

        data.to_csv(county_file, index=False)
        
        print("Saved")

    except Exception as error:
        print("Failed:", error)
        
    # all_weather_data.append(data)

    time.sleep(0.1)

0/1124: 17011 already completed
1/1124: 17015 already completed
2/1124: 17073 already completed
3/1124: 17085 already completed
4/1124: 17103 already completed
5/1124: 17131 already completed
6/1124: 17141 already completed
7/1124: 17155 already completed
8/1124: 17161 already completed
9/1124: 17177 already completed
10/1124: 17195 already completed
11/1124: 17201 already completed
12/1124: 17007 already completed
13/1124: 17031 already completed
14/1124: 17037 already completed
15/1124: 17043 already completed
16/1124: 17063 already completed
17/1124: 17089 already completed
18/1124: 17093 already completed
19/1124: 17097 already completed
20/1124: 17099 already completed
21/1124: 17111 already completed
22/1124: 17197 already completed
23/1124: 17001 already completed
24/1124: 17009 already completed
25/1124: 17057 already completed
26/1124: 17067 already completed
27/1124: 17071 already completed
28/1124: 17095 already completed
29/1124: 17109 already completed
30/1124: 17169 already completed
31/1124: 17187 already completed
32/1124: 17039 already completed
33/1124: 17107 already completed
34/1124: 17113 already completed
35/1124: 17115 already completed
36/1124: 17123 already completed
37/1124: 17125 already completed
38/1124: 17129 already completed
39/1124: 17143 already completed
40/1124: 17175 already completed
41/1124: 17179 already completed
42/1124: 17203 already completed
43/1124: 17019 already completed
44/1124: 17053 already completed
45/1124: 17075 already completed
46/1124: 17091 already completed
47/1124: 17105 already completed
48/1124: 17147 already completed
49/1124: 17183 already completed
50/1124: 17005 already completed
51/1124: 17013 already completed
52/1124: 17017 already completed
53/1124: 17021 already completed
54/1124: 17061 already completed
55/1124: 17083 already completed
56/1124: 17117 already completed
57/1124: 17119 already completed
58/1124: 17135 already completed
59/1124: 17137 already completed
60/1124: 17149 already completed
61/1124: 17167 already completed
62/1124: 17171 already completed
63/1124: 17023 already completed
64/1124: 17025 already completed
65/1124: 17029 already completed
66/1124: 17033 already completed
67/1124: 17035 already completed
68/1124: 17041 already completed
69/1124: 17045 already completed
70/1124: 17049 already completed
71/1124: 17051 already completed
72/1124: 17079 already completed
73/1124: 17101 already completed
74/1124: 17121 already completed
75/1124: 17139 already completed
76/1124: 17159 already completed
77/1124: 17173 already completed
78/1124: 17003 already completed
79/1124: 17027 already completed
80/1124: 17077 already completed
81/1124: 17087 already completed
82/1124: 17133 already completed
83/1124: 17145 already completed
84/1124: 17153 already completed
85/1124: 17157 already completed
86/1124: 17163 already completed
87/1124: 17181 already completed
88/1124: 17189 already completed
89/1124: 17199 already completed
90/1124: 17047 already completed
91/1124: 17055 already completed
92/1124: 17059 already completed
93/1124: 17065 already completed
94/1124: 17069 already completed
95/1124: 17081 already completed
96/1124: 17127 already completed
97/1124: 17151 already completed
98/1124: 17165 already completed
99/1124: 17185 already completed
100/1124: 17191 already completed
101/1124: 17193 already completed
102/1124: 18007 already completed
103/1124: 18073 already completed
104/1124: 18089 already completed
105/1124: 18091 already completed
106/1124: 18111 already completed
107/1124: 18127 already completed
108/1124: 18131 already completed
109/1124: 18149 already completed
110/1124: 18181 already completed
111/1124: 18015 already completed
112/1124: 18017 already completed
113/1124: 18039 already completed
114/1124: 18049 already completed
115/1124: 18085 already completed
116/1124: 18099 already completed
117/1124: 18103 already completed
118/1124: 18141 already completed
119/1124: 18169 already completed
120/1124: 18001 already completed
121/1124: 18003 already completed
122/1124: 18033 already completed
123/1124: 18069 already completed
124/1124: 18087 already completed
125/1124: 18113 already completed
126/1124: 18151 already completed
127/1124: 18179 already completed
128/1124: 18183 already completed
129/1124: 18021 already completed
130/1124: 18045 already completed
131/1124: 18107 already completed
132/1124: 18119 already completed
133/1124: 18121 already completed
134/1124: 18133 already completed
135/1124: 18157 already completed
136/1124: 18165 already completed
137/1124: 18167 already completed
138/1124: 18171 already completed
139/1124: 18005 already completed
140/1124: 18011 already completed
141/1124: 18023 already completed
142/1124: 18031 already completed
143/1124: 18053 already completed
144/1124: 18057 already completed
145/1124: 18059 already completed
146/1124: 18063 already completed
147/1124: 18067 already completed
148/1124: 18081 already completed
149/1124: 18095 already completed
150/1124: 18097 already completed
151/1124: 18109 already completed
152/1124: 18139 already completed
153/1124: 18145 already completed
154/1124: 18159 already completed
155/1124: 18009 already completed
156/1124: 18035 already completed
157/1124: 18041 already completed
158/1124: 18065 already completed
159/1124: 18075 already completed
160/1124: 18135 already completed
161/1124: 18161 already completed
162/1124: 18177 already completed
163/1124: 18027 already completed
164/1124: 18037 already completed
165/1124: 18051 already completed
166/1124: 18055 already completed
167/1124: 18083 already completed
168/1124: 18101 already completed
169/1124: 18125 already completed
170/1124: 18129 already completed
171/1124: 18147 already completed
172/1124: 18153 already completed
173/1124: 18163 already completed
174/1124: 18173 already completed
175/1124: 18013 already completed
176/1124: 18025 already completed
177/1124: 18043 already completed
178/1124: 18061 already completed
179/1124: 18071 already completed
180/1124: 18093 already completed
181/1124: 18105 already completed
182/1124: 18117 already completed
183/1124: 18123 already completed
184/1124: 18175 already completed
185/1124: 18019 already completed
186/1124: 18029 already completed
187/1124: 18047 already completed
188/1124: 18077 already completed
189/1124: 18079 already completed
190/1124: 18115 already completed
191/1124: 18137 already completed
192/1124: 18143 already completed
193/1124: 18155 already completed
194/1124: 19021 already completed
195/1124: 19035 already completed
196/1124: 19041 already completed
197/1124: 19059 already completed
198/1124: 19063 already completed
199/1124: 19119 already completed
200/1124: 19141 already completed
201/1124: 19143 already completed
202/1124: 19147 already completed
203/1124: 19149 already completed
204/1124: 19151 already completed
205/1124: 19167 already completed
206/1124: 19023 already completed
207/1124: 19033 already completed
208/1124: 19067 already completed
209/1124: 19069 already completed
210/1124: 19081 already completed
211/1124: 19091 already completed
212/1124: 19109 already completed
213/1124: 19131 already completed
214/1124: 19189 already completed
215/1124: 19195 already completed
216/1124: 19197 already completed
217/1124: 19005 already completed
218/1124: 19013 already completed
219/1124: 19017 already completed
220/1124: 19019 already completed
221/1124: 19037 already completed
222/1124: 19043 already completed
223/1124: 19055 already completed
224/1124: 19061 already completed
225/1124: 19065 already completed
226/1124: 19089 already completed
227/1124: 19191 already completed
228/1124: 19009 already completed
229/1124: 19025 already completed
230/1124: 19027 already completed
231/1124: 19047 already completed
232/1124: 19073 already completed
233/1124: 19077 already completed
234/1124: 19085 already completed
235/1124: 19093 already completed
236/1124: 19133 already completed
237/1124: 19161 already completed
238/1124: 19165 already completed
239/1124: 19193 already completed
240/1124: 19015 already completed
241/1124: 19049 already completed
242/1124: 19075 already completed
243/1124: 19079 already completed
244/1124: 19083 already completed
245/1124: 19099 already completed
246/1124: 19127 already completed
247/1124: 19153 already completed
248/1124: 19157 already completed
249/1124: 19169 already completed
250/1124: 19171 already completed
251/1124: 19187 already completed
252/1124: 19011 already completed
253/1124: 19031 already completed
254/1124: 19045 already completed
255/1124: 19095 already completed
256/1124: 19097 already completed
257/1124: 19103 already completed
258/1124: 19105 already completed
259/1124: 19113 already completed
260/1124: 19139 already completed
261/1124: 19163 already completed
262/1124: 19001 already completed
263/1124: 19003 already completed
264/1124: 19029 already completed
265/1124: 19071 already completed
266/1124: 19129 already completed
267/1124: 19137 already completed
268/1124: 19145 already completed
269/1124: 19155 already completed
270/1124: 19173 already completed
271/1124: 19007 already completed
272/1124: 19039 already completed
273/1124: 19053 already completed
274/1124: 19117 already completed
275/1124: 19121 already completed
276/1124: 19125 already completed
277/1124: 19135 already completed
278/1124: 19159 already completed
279/1124: 19175 already completed
280/1124: 19181 already completed
281/1124: 19185 already completed
282/1124: 19051 already completed
283/1124: 19057 already completed
284/1124: 19087 already completed
285/1124: 19101 already completed
286/1124: 19107 already completed
287/1124: 19111 already completed
288/1124: 19115 already completed
289/1124: 19123 already completed
290/1124: 19177 already completed
291/1124: 19179 already completed
292/1124: 19183 already completed
293/1124: 20023 already completed
294/1124: 20039 already completed
295/1124: 20065 already completed
296/1124: 20137 already completed
297/1124: 20153 already completed
298/1124: 20179 already completed
299/1124: 20181 already completed
300/1124: 20193 already completed
301/1124: 20063 already completed
302/1124: 20071 already completed
303/1124: 20101 already completed
304/1124: 20109 already completed
305/1124: 20135 already completed
306/1124: 20171 already completed
307/1124: 20195 already completed
308/1124: 20199 already completed
309/1124: 20203 already completed
310/1124: 20025 already completed
311/1124: 20055 already completed
312/1124: 20057 already completed
313/1124: 20067 already completed
314/1124: 20069 already completed
315/1124: 20075 already completed
316/1124: 20081 already completed
317/1124: 20083 already completed
318/1124: 20093 already completed
319/1124: 20119 already completed
320/1124: 20129 already completed
321/1124: 20175 already completed
322/1124: 20187 already completed
323/1124: 20189 already completed
324/1124: 20027 already completed
325/1124: 20029 already completed
326/1124: 20089 already completed
327/1124: 20123 already completed
328/1124: 20141 already completed
329/1124: 20143 already completed
330/1124: 20147 already completed
331/1124: 20157 already completed
332/1124: 20163 already completed
333/1124: 20183 already completed
334/1124: 20201 already completed
335/1124: 20009 already completed
336/1124: 20041 already completed
337/1124: 20051 already completed
338/1124: 20053 already completed
339/1124: 20105 already completed
340/1124: 20113 already completed
341/1124: 20115 already completed
342/1124: 20159 already completed
343/1124: 20165 already completed
344/1124: 20167 already completed
345/1124: 20169 already completed
346/1124: 20007 already completed
347/1124: 20033 already completed
348/1124: 20047 already completed
349/1124: 20077 already completed
350/1124: 20079 already completed
351/1124: 20095 already completed
352/1124: 20097 already completed
353/1124: 20145 already completed
354/1124: 20151 already completed
355/1124: 20155 already completed
356/1124: 20173 already completed
357/1124: 20185 already completed
358/1124: 20191 already completed
359/1124: 20005 already completed
360/1124: 20013 already completed
361/1124: 20043 already completed
362/1124: 20085 already completed
363/1124: 20087 already completed
364/1124: 20103 already completed
365/1124: 20117 already completed
366/1124: 20131 already completed
367/1124: 20149 already completed
368/1124: 20161 already completed
369/1124: 20209 already completed
370/1124: 20003 already completed
371/1124: 20017 already completed
372/1124: 20031 already completed
373/1124: 20045 already completed
374/1124: 20059 already completed
375/1124: 20061 already completed
376/1124: 20091 already completed
377/1124: 20107 already completed
378/1124: 20111 already completed
379/1124: 20121 already completed
380/1124: 20127 already completed
381/1124: 20139 already completed
382/1124: 20177 already completed
383/1124: 20197 already completed
384/1124: 20001 already completed
385/1124: 20011 already completed
386/1124: 20015 already completed
387/1124: 20019 already completed
388/1124: 20021 already completed
389/1124: 20035 already completed
390/1124: 20037 already completed
391/1124: 20049 already completed
392/1124: 20073 already completed
393/1124: 20099 already completed
394/1124: 20125 already completed
395/1124: 20133 already completed
396/1124: 20205 already completed
397/1124: 20207 already completed
398/1124: 21007 already completed
399/1124: 21035 already completed
400/1124: 21039 already completed
401/1124: 21075 already completed
402/1124: 21083 already completed
403/1124: 21105 already completed
404/1124: 21139 already completed
405/1124: 21143 already completed
406/1124: 21145 already completed
407/1124: 21157 already completed
408/1124: 21221 already completed
409/1124: 21033 already completed
410/1124: 21047 already completed
411/1124: 21055 already completed
412/1124: 21059 already completed
413/1124: 21091 already completed
414/1124: 21101 already completed
415/1124: 21107 already completed
416/1124: 21141 already completed
417/1124: 21149 already completed
418/1124: 21177 already completed
419/1124: 21183 already completed
420/1124: 21213 already completed
421/1124: 21219 already completed
422/1124: 21225 already completed
423/1124: 21233 already completed
424/1124: 21001 already completed
425/1124: 21003 already completed
426/1124: 21009 already completed
427/1124: 21027 already completed
428/1124: 21029 already completed
429/1124: 21031 already completed
430/1124: 21045 already completed
431/1124: 21053 already completed
432/1124: 21057 already completed
433/1124: 21061 already completed
434/1124: 21085 already completed
435/1124: 21087 already completed
436/1124: 21093 already completed
437/1124: 21099 already completed
438/1124: 21111 already completed
439/1124: 21123 already completed
440/1124: 21155 already completed
441/1124: 21163 already completed
442/1124: 21169 already completed
443/1124: 21171 already completed
444/1124: 21179 already completed
445/1124: 21207 already completed
446/1124: 21217 already completed
447/1124: 21227 already completed
448/1124: 21015 already completed
449/1124: 21023 already completed
450/1124: 21037 already completed
451/1124: 21041 already completed
452/1124: 21077 already completed
453/1124: 21081 already completed
454/1124: 21103 already completed
455/1124: 21117 already completed
456/1124: 21185 already completed
457/1124: 21187 already completed
458/1124: 21191 already completed
459/1124: 21223 already completed
460/1124: 21005 already completed
461/1124: 21011 already completed
462/1124: 21017 already completed
463/1124: 21021 already completed
464/1124: 21049 already completed
465/1124: 21067 already completed
466/1124: 21069 already completed
467/1124: 21073 already completed
468/1124: 21079 already completed
469/1124: 21097 already completed
470/1124: 21113 already completed
471/1124: 21137 already completed
472/1124: 21151 already completed
473/1124: 21161 already completed
474/1124: 21167 already completed
475/1124: 21173 already completed
476/1124: 21181 already completed
477/1124: 21201 already completed
478/1124: 21209 already completed
479/1124: 21211 already completed
480/1124: 21215 already completed
481/1124: 21229 already completed
482/1124: 21239 already completed
483/1124: 21025 already completed
484/1124: 21043 already completed
485/1124: 21051 already completed
486/1124: 21063 already completed
487/1124: 21065 already completed
488/1124: 21089 already completed
489/1124: 21109 already completed
490/1124: 21115 already completed
491/1124: 21121 already completed
492/1124: 21125 already completed
493/1124: 21135 already completed
494/1124: 21153 already completed
495/1124: 21165 already completed
496/1124: 21175 already completed
497/1124: 21189 already completed
498/1124: 21197 already completed
499/1124: 21199 already completed
500/1124: 21203 already completed
501/1124: 21205 already completed
502/1124: 21231 already completed
503/1124: 21235 already completed
504/1124: 21237 already completed
505/1124: 26041 already completed
506/1124: 26043 already completed
507/1124: 26103 already completed
508/1124: 26109 already completed
509/1124: 26009 already completed
510/1124: 26019 already completed
511/1124: 26029 already completed
512/1124: 26047 already completed
513/1124: 26055 already completed
514/1124: 26079 already completed
515/1124: 26089 already completed
516/1124: 26101 already completed
517/1124: 26113 already completed
518/1124: 26165 already completed
519/1124: 26001 already completed
520/1124: 26007 already completed
521/1124: 26031 already completed
522/1124: 26069 already completed
523/1124: 26119 already completed
524/1124: 26129 already completed
525/1124: 26135 already completed
526/1124: 26137 already completed
527/1124: 26141 already completed
528/1124: 26085 already completed
529/1124: 26105 already completed
530/1124: 26121 already completed
531/1124: 26123 already completed
532/1124: 26127 already completed
533/1124: 26035 already completed
534/1124: 26051 already completed
535/1124: 26057 already completed
536/1124: 26073 already completed
537/1124: 26107 already completed
538/1124: 26111 already completed
539/1124: 26117 already completed
540/1124: 26133 already completed
541/1124: 26011 already completed
542/1124: 26017 already completed
543/1124: 26063 already completed
544/1124: 26145 already completed
545/1124: 26151 already completed
546/1124: 26157 already completed
547/1124: 26005 already completed
548/1124: 26021 already completed
549/1124: 26027 already completed
550/1124: 26077 already completed
551/1124: 26081 already completed
552/1124: 26139 already completed
553/1124: 26159 already completed
554/1124: 26015 already completed
555/1124: 26023 already completed
556/1124: 26025 already completed
557/1124: 26037 already completed
558/1124: 26045 already completed
559/1124: 26059 already completed
560/1124: 26065 already completed
561/1124: 26067 already completed
562/1124: 26075 already completed
563/1124: 26149 already completed
564/1124: 26155 already completed
565/1124: 26049 already completed
566/1124: 26087 already completed
567/1124: 26091 already completed
568/1124: 26093 already completed
569/1124: 26099 already completed
570/1124: 26115 already completed
571/1124: 26125 already completed
572/1124: 26147 already completed
573/1124: 26161 already completed
574/1124: 26163 already completed
575/1124: 27005 already completed
576/1124: 27027 already completed
577/1124: 27029 already completed
578/1124: 27069 already completed
579/1124: 27087 already completed
580/1124: 27089 already completed
581/1124: 27107 already completed
582/1124: 27113 already completed
583/1124: 27119 already completed
584/1124: 27125 already completed
585/1124: 27135 already completed
586/1124: 27007 already completed
587/1124: 27021 already completed
588/1124: 27057 already completed
589/1124: 27061 already completed
590/1124: 27071 already completed

### Combine all lof the weather files

In [21]:
all_weather_data = []

for filename in os.listdir("daymet_counties"):
    if filename.endswith(".csv"):
        data = pd.read_csv(f"daymet_counties/{filename}", dtype={"fips": str})
        all_weather_data.append(data)

In [22]:
weather_df = pd.concat(all_weather_data, ignore_index=True)
weather_df.head()

,year,yday,dayl (s),prcp (mm/day),srad (W/m^2),swe (kg/m^2),tmax (deg c),tmin (deg c),vp (Pa),fips,latitude,longitude
0,2000,1,30470.40,13.66,125.50,111.96,-1.81,-11.57,252.27,26103,46.4313,-87.6416
1,2000,2,30524.32,15.97,67.20,127.93,-1.97,-6.53,374.84,26103,46.4313,-87.6416
2,2000,3,30582.63,3.26,52.46,131.19,-3.06,-6.49,375.82,26103,46.4313,-87.6416
3,2000,4,30645.28,2.16,76.78,133.35,-5.59,-10.71,270.14,26103,46.4313,-87.6416
4,2000,5,30712.22,0.00,227.57,133.35,-5.69,-23.06,95.43,26103,46.4313,-87.6416

In [23]:
weather_df.tail()

,year,yday,dayl (s),prcp (mm/day),srad (W/m^2),swe (kg/m^2),tmax (deg c),tmin (deg c),vp (Pa),fips,latitude,longitude
10666755,2025,361,31357.98,1.45,46.35,25.35,2.11,0.21,619.97,55137,44.1131,-89.2429
10666756,2025,362,31386.34,13.63,50.90,23.34,1.83,-1.21,559.15,55137,44.1131,-89.2429
10666757,2025,363,31418.83,0.00,91.19,23.34,-5.28,-9.34,301.20,55137,44.1131,-89.2429
10666758,2025,364,31455.43,1.78,177.55,25.12,-5.17,-14.04,206.45,55137,44.1131,-89.2429
10666759,2025,365,31496.12,1.00,213.06,26.12,-1.91,-14.17,204.16,55137,44.1131,-89.2429

In [24]:
weather_df.columns

Index(['year', 'yday', 'dayl (s)', 'prcp (mm/day)', 'srad (W/m^2)',
       'swe (kg/m^2)', 'tmax (deg c)', 'tmin (deg c)', 'vp (Pa)', 'fips',
       'latitude', 'longitude'],
      dtype='object')

### What do these mean?

**`dayl`** ( Day Length (seconds/day (s/day) ) ) - Duration of the daylight period for the day. This calculation is based on the period of the day during which the sun is above a hypothetical flat horizon.

**`prcp`** ( Precipitation (millimeters/day (mm/day) ) ) - Daily total precipitation, sum of all forms converted to water-equivalent.

**`srad`** ( Shortwave Solar Radiation (watts per square meter (W/m²) ) ) - Amount of incoming shortwave solar energy reaching the surface. Daymet reports the **average radiation flux during daylight hours**, rather than an average over the entire 24-hour day.

**`swe`** ( Snow Water Equivalent (kilograms per square meter (kg/m²) ) ) - Snow water equivalent. The amount of water contained within the snowpack.

**`tmax`** ( Maximum Air Temperature (degrees Celsius (°C) ) ) - Daily maximum 2-meter air temperature.

**`tmin`** ( Minimum Air Temperature (degrees Celsius (°C) ) ) - Daily minimum 2-meter air temperature.

**`vp`** ( Water Vapor Pressure (Pascals (Pa) ) ) - Water Vapor Pressure. Daily average partial pressure of water vapor.

**Note:** Daily Total Radiation (MJ/m^2/day) can be calculated: ((srad (W/m^2) * dayl (s/day)) / l,000,000)

In [25]:
weather_df.shape

(10666760, 12)

In [26]:
# rename the columns
weather_df = weather_df.rename(columns={
    'dayl (s)': 'dayl_s', 
    'prcp (mm/day)': 'prcp_mm_day', 
    'srad (W/m^2)': 'srad_w_m2',
    'swe (kg/m^2)': 'swe_kg_m2', 
    'tmax (deg c)': 'tmax_c', 
    'tmin (deg c)': 'tmin_c', 
    'vp (Pa)': 'vp_pa'
})

In [27]:
weather_df["date"] = (pd.to_datetime(weather_df["year"], format="%Y") + pd.to_timedelta(weather_df["yday"] - 1, unit="D"))
weather_df["month"] = weather_df["date"].dt.month

In [28]:
weather_df.head()

,year,yday,dayl_s,prcp_mm_day,srad_w_m2,swe_kg_m2,tmax_c,tmin_c,vp_pa,fips,latitude,longitude,date,month
0,2000,1,30470.40,13.66,125.50,111.96,-1.81,-11.57,252.27,26103,46.4313,-87.6416,2000-01-01,1
1,2000,2,30524.32,15.97,67.20,127.93,-1.97,-6.53,374.84,26103,46.4313,-87.6416,2000-01-02,1
2,2000,3,30582.63,3.26,52.46,131.19,-3.06,-6.49,375.82,26103,46.4313,-87.6416,2000-01-03,1
3,2000,4,30645.28,2.16,76.78,133.35,-5.59,-10.71,270.14,26103,46.4313,-87.6416,2000-01-04,1
4,2000,5,30712.22,0.00,227.57,133.35,-5.69,-23.06,95.43,26103,46.4313,-87.6416,2000-01-05,1

In [29]:
# Calculate Solar Radiation
weather_df["radiation_mj_m2_day"] = weather_df["srad_w_m2"] * weather_df["dayl_s"] / 1_000_000

In [30]:
monthly_weather = weather_df.groupby(["fips", "year", "month"],as_index=False).agg(
    prcp_total_mm=("prcp_mm_day", "sum"),
    radiation_total_mj_m2=("radiation_mj_m2_day", "sum"),
    dayl_mean_s=("dayl_s", "mean"),
    swe_mean_kg_m2=("swe_kg_m2", "mean"),
    tmax_mean_c=("tmax_c", "mean"),
    tmin_mean_c=("tmin_c", "mean"),
    vp_mean_pa=("vp_pa", "mean"),
)

In [31]:
monthly_weather.head()

,fips,year,month,prcp_total_mm,radiation_total_mj_m2,dayl_mean_s,swe_mean_kg_m2,tmax_mean_c,tmin_mean_c,vp_mean_pa
0,17001,2000,1,19.61,233.077019,34257.320645,5.646774,2.590645,-7.356452,380.588065
1,17001,2000,2,79.19,298.927736,37762.033448,1.913103,9.046207,-1.495862,572.198276
2,17001,2000,3,46.96,447.767132,42394.024516,0.000000,13.606774,1.701935,703.285806
3,17001,2000,4,33.59,568.288936,47234.612333,0.000000,18.121667,4.885667,840.521000
4,17001,2000,5,77.09,639.980684,51282.445484,0.000000,24.685806,12.448065,1381.315484

In [32]:
# Turn each month into a column
monthly_weather = monthly_weather.pivot(
    index=["fips", "year"],
    columns="month"
)

In [33]:
monthly_weather.head()

           prcp_total_mm                                                \
month                 1      2      3       4       5       6       7
fips  year
17001 2000         19.61  79.19  46.96   33.59   77.09  196.25   85.81
      2001         84.65  91.46  46.37   82.85  145.02  110.94   54.68
      2002         78.13  29.34  35.35  138.66  238.94   97.42  123.64
      2003         33.10  36.36  53.15   99.04   86.30  108.88  124.66
      2004         18.83  18.87  80.74   62.27  129.39   76.41   78.78

                                   ...  vp_mean_pa                            \
month           8      9       10  ...          3            4            5
fips  year                         ...
17001 2000  120.91  60.52   62.42  ...  703.285806   840.521000  1381.315484
      2001  134.37  84.49  106.29  ...  496.050645  1115.226000  1493.618710
      2002  118.20  13.96   88.94  ...  508.791935   992.366000  1203.445484
      2003  132.89  98.73   48.05  ...  560.998710   924.592667  1280.123226
      2004  229.61  28.77  163.48  ...  684.761613   890.752667  1496.920323

                                                                             \
month                6            7            8            9            10
fips  year
17001 2000  1766.777000  2139.278065  2218.254839  1550.184000  1150.944516
      2001  1819.425000  2299.301935  2048.718065  1451.843000   987.571935
      2002  2065.985667  2358.078710  2131.864194  1593.893333   942.513548
      2003  1692.230000  2137.109677  2155.233871  1342.730333   977.849677
      2004  1788.652333  2016.278710  1671.298065  1501.030333  1053.663871


month               11          12
fips  year
17001 2000  580.671333  240.422667
      2001  865.225667  547.358710
      2002  581.450000  438.044194
      2003  685.048667  482.509677
      2004  764.416667  438.501667

[5 rows x 84 columns]

In [34]:
monthly_weather.columns = [
    f"{weather_variable}_m{month:02d}"
    for weather_variable, month
    in monthly_weather.columns
]

In [35]:
monthly_weather.head()

            prcp_total_mm_m01  prcp_total_mm_m02  prcp_total_mm_m03  \
fips  year
17001 2000              19.61              79.19              46.96
      2001              84.65              91.46              46.37
      2002              78.13              29.34              35.35
      2003              33.10              36.36              53.15
      2004              18.83              18.87              80.74

            prcp_total_mm_m04  prcp_total_mm_m05  prcp_total_mm_m06  \
fips  year
17001 2000              33.59              77.09             196.25
      2001              82.85             145.02             110.94
      2002             138.66             238.94              97.42
      2003              99.04              86.30             108.88
      2004              62.27             129.39              76.41

            prcp_total_mm_m07  prcp_total_mm_m08  prcp_total_mm_m09  \
fips  year
17001 2000              85.81             120.91              60.52
      2001              54.68             134.37              84.49
      2002             123.64             118.20              13.96
      2003             124.66             132.89              98.73
      2004              78.78             229.61              28.77

            prcp_total_mm_m10  ...  vp_mean_pa_m03  vp_mean_pa_m04  \
fips  year                     ...
17001 2000              62.42  ...      703.285806      840.521000
      2001             106.29  ...      496.050645     1115.226000
      2002              88.94  ...      508.791935      992.366000
      2003              48.05  ...      560.998710      924.592667
      2004             163.48  ...      684.761613      890.752667

            vp_mean_pa_m05  vp_mean_pa_m06  vp_mean_pa_m07  vp_mean_pa_m08  \
fips  year
17001 2000     1381.315484     1766.777000     2139.278065     2218.254839
      2001     1493.618710     1819.425000     2299.301935     2048.718065
      2002     1203.445484     2065.985667     2358.078710     2131.864194
      2003     1280.123226     1692.230000     2137.109677     2155.233871
      2004     1496.920323     1788.652333     2016.278710     1671.298065

            vp_mean_pa_m09  vp_mean_pa_m10  vp_mean_pa_m11  vp_mean_pa_m12
fips  year
17001 2000     1550.184000     1150.944516      580.671333      240.422667
      2001     1451.843000      987.571935      865.225667      547.358710
      2002     1593.893333      942.513548      581.450000      438.044194
      2003     1342.730333      977.849677      685.048667      482.509677
      2004     1501.030333     1053.663871      764.416667      438.501667

[5 rows x 84 columns]

In [36]:
monthly_weather = monthly_weather.reset_index()

In [37]:
monthly_weather.head()

,fips,year,prcp_total_mm_m01,prcp_total_mm_m02,prcp_total_mm_m03,prcp_total_mm_m04,prcp_total_mm_m05,prcp_total_mm_m06,prcp_total_mm_m07,prcp_total_mm_m08,...,vp_mean_pa_m03,vp_mean_pa_m04,vp_mean_pa_m05,vp_mean_pa_m06,vp_mean_pa_m07,vp_mean_pa_m08,vp_mean_pa_m09,vp_mean_pa_m10,vp_mean_pa_m11,vp_mean_pa_m12
0,17001,2000,19.61,79.19,46.96,33.59,77.09,196.25,85.81,120.91,...,703.285806,840.521000,1381.315484,1766.777000,2139.278065,2218.254839,1550.184000,1150.944516,580.671333,240.422667
1,17001,2001,84.65,91.46,46.37,82.85,145.02,110.94,54.68,134.37,...,496.050645,1115.226000,1493.618710,1819.425000,2299.301935,2048.718065,1451.843000,987.571935,865.225667,547.358710
2,17001,2002,78.13,29.34,35.35,138.66,238.94,97.42,123.64,118.20,...,508.791935,992.366000,1203.445484,2065.985667,2358.078710,2131.864194,1593.893333,942.513548,581.450000,438.044194
3,17001,2003,33.10,36.36,53.15,99.04,86.30,108.88,124.66,132.89,...,560.998710,924.592667,1280.123226,1692.230000,2137.109677,2155.233871,1342.730333,977.849677,685.048667,482.509677
4,17001,2004,18.83,18.87,80.74,62.27,129.39,76.41,78.78,229.61,...,684.761613,890.752667,1496.920323,1788.652333,2016.278710,1671.298065,1501.030333,1053.663871,764.416667,438.501667

### Save to .csv

In [38]:
weather_df.to_csv('corn_belt_weather.csv', index=False)

---

## Merge with corn yield data

In [39]:
yield_df["fips"] = (yield_df["fips"].astype(str).str.zfill(5))

monthly_weather["fips"] = (monthly_weather["fips"].astype(str).str.zfill(5))

yield_df["year"] = yield_df["year"].astype(int)
monthly_weather["year"] = monthly_weather["year"].astype(int)

In [40]:
final_df = yield_df.merge(
    monthly_weather,
    on=["fips", "year"],
    how="left",
    validate="one_to_one"
)

In [41]:
print("Yield rows:", len(yield_df))
print("Final rows:", len(final_df))

Yield rows: 24644
Final rows: 24644

## Save to .csv

In [42]:
final_df.to_csv('corn_belt_yield_weather.csv', index=False)